### ISSUE TITLE
Branding - Logo

### ISSUE THREAD

**Issue by harrycopeman** [CycleStudios/Robin#1]
A place for us to discuss and iterate on the logo.

**Comment by harrycopeman** [comment]
Here's a mood board of logo's, I'd love Robin to adopt this style.

![logos](https://cloud.githubusercontent.com/assets/6804391/12923745/c3caa544-cf4e-11e5-9675-60afe1f45887.png)

**Comment by wlenzenjr** [comment]
![slack_for_ios_upload](https://cloud.githubusercontent.com/assets/9578832/12932761/09f48972-cf4a-11e5-8b0e-b786dc7a941d.jpg)

**Comment by wlenzenjr** [comment]
Played around with a simple icon idea (your glyph find was really inspiring), as well as researched some fonts and came up with this:

<img width="1040" alt="screen shot 2016-02-09 at 11 34 16 pm" src="https://cloud.githubusercontent.com/assets/9578832/12939482/bcc14bcc-cf85-11e5-9531-a6060f01d06f.png">

It's a base font of Halis Rounded. I'd customize it if we were to use it - but I quite like it as a base font. What do you think?

**Comment by harrycopeman** [comment]
So I really really like this icon, it could probably be a little thinner but it works. One question, is there a meaning behind this?

Regarding the typeface, I don't love it :/ We can do a better job of doing something that doesn't look mainstream :smile: I'm happy to try this, sick work on the icon! Also let's alway have it on the left :wink:

Or... one thing I like about Figma is that on their site they just use the type, then on social they just use the icon - I feel like it works well.

**Comment by harrycopeman** [comment]
Here's one quick pass at it.
![logo](https://cloud.githubusercontent.com/assets/6804391/12945833/fc4a49f8-cfe7-11e5-92dd-ceb3984e8db0.png)

**Comment by wlenzenjr** [comment]
What typeface is that? I'm _really_ not a fan of the serif logo, but I'm willing to play with it and am exploring it today.

**Comment by harrycopeman** [comment]
@wlenzenjr It's Adriane - also not loving it but the sans-serif's ain't working right now. Can we try something close to http://bakkenbaeck.com/?

**Comment by wlenzenjr** [comment]
The Bakken Baeck logo is really pointy and harsh though. Doesn't seem to match what we've established with the Robin interface. I'd rather have a serif font than something as harsh as the BB logo. I'm exploring Typekit now.

As for the icon, glad you like it. There's actually a lot of meaning in the icon:
- circle: balance
- the line spacing (of my design): consistency
- the dot: goals
- the shorter line: determination

**Comment by harrycopeman** [comment]
I actually think the typeface in our interface is pretty tough and hard, and I like it. Also here's a point, do we need the wordmark too? So many examples I could send to prove that no is a decent answer, here's one - https://claralabs.com/

Great about the icon, it also reminds me of levers in way, which means 'control'.

**Comment by wlenzenjr** [comment]
After playing around with this briefly I agree. Let's keep the robin wordmark as Colfax type set at either lowercase medium, or Robin bold.
<img width="636" alt="screen shot 2016-02-10 at 8 44 56 am" src="https://cloud.githubusercontent.com/assets/9578832/12950462/e8868de2-cfd2-11e5-81ba-b79a56668a82.png">

**Comment by wlenzenjr** [comment]
<img width="721" alt="screen shot 2016-02-10 at 8 54 49 am" src="https://cloud.githubusercontent.com/assets/9578832/12950695/fe626248-cfd3-11e5-828c-39998dff56e5.png">
I think the stroke on the icon could be a bit thicker still. What do you think?

**Comment by wlenzenjr** [comment]
Here's what that would look like:
<img width="809" alt="screen shot 2016-02-10 at 10 00 01 am" src="https://cloud.githubusercontent.com/assets/9578832/12952725/1bc6fdf4-cfdd-11e5-8467-e580ad034b68.png">

**Comment by harrycopeman** [comment]
We're game, sign this off.

**Comment by wlenzenjr** [comment]
Awesome, here's our assets:
<img width="896" alt="screen shot 2016-02-11 at 10 36 27 am" src="https://cloud.githubusercontent.com/assets/9578832/12982673/6ba80772-d0ab-11e5-9a1b-92bb96da8379.png">
